spin_manifest_version = "1"
authors = ["Bryce <>"]
description = "a go snake using wasm"
name = "wasm_go_snake"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "wasm-go-snake"
source = "main.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
